import { DOCUMENT } from '@angular/common';
import { Component, inject, signal, type OnDestroy } from '@angular/core';
import { TngStepperComponent, TngStepperItemComponent } from '@tailng-ui/components';
import {
  TngStepperDescription,
  TngStepperItem,
  TngStepperLabel,
  TngStepperTrigger,
} from '@tailng-ui/primitives';
import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';
import {
  DocsExampleTabsSectionComponent,
  DocsExampleVariantDirective,
} from '../../../../../../shared/example-tabs-section/docs-example-tabs-section.component';
import {
  observeDocsCodeThemeChanges,
  resolveDocsCodeBlockTheme,
} from '../../../../../../shared/util';

@Component({
  selector: 'app-stepper-examples-page',
  imports: [
    TngStepperComponent,
    TngStepperItemComponent,
    TngStepperDescription,
    TngStepperItem,
    TngStepperLabel,
    TngStepperTrigger,
    DocsExampleTabsSectionComponent,
    DocsExampleVariantDirective,
  ],
  templateUrl: './stepper-examples-page.component.html',
  styleUrl: './stepper-examples-page.component.css',
})
export class StepperExamplesPageComponent implements OnDestroy {
  private readonly documentRef = inject(DOCUMENT);

  public readonly codeBlockTheme = signal<'github-dark' | 'github-light'>(
    resolveDocsCodeBlockTheme(this.documentRef),
  );
  private readonly colorSchemeObserver = observeDocsCodeThemeChanges(this.documentRef, this.codeBlockTheme);

  protected readonly horizontalPlainCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'stepper-examples-horizontal-plain-css.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import { TngStepperComponent, TngStepperItemComponent } from '@tailng-ui/components';",
        '',
        '@Component({',
        "  selector: 'app-stepper-examples-horizontal-plain-css',",
        '  standalone: true,',
        '  imports: [TngStepperComponent, TngStepperItemComponent],',
        "  templateUrl: './stepper-examples-horizontal-plain-css.component.html',",
        "  styleUrl: './stepper-examples-horizontal-plain-css.component.css',",
        '})',
        'export class StepperExamplesHorizontalPlainCssComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'stepper-examples-horizontal-plain-css.component.html',
      code: [
        '<div class="stepper-example-shell stepper-example-shell--plain stepper-example-shell--horizontal">',
        '  <tng-stepper orientation="horizontal" defaultValue="plan" ariaLabel="Horizontal onboarding progress">',
        '    <tng-stepper-item value="account" label="Account" completed />',
        '    <tng-stepper-item value="plan" label="Plan" description="Choose workspace limits" />',
        '    <tng-stepper-item value="invite" label="Invite" description="Optional team setup" optional />',
        '  </tng-stepper>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'stepper-examples-horizontal-plain-css.component.css',
      code: [
        '.stepper-example-shell--horizontal {',
        '  max-width: 48rem;',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly horizontalTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'stepper-examples-horizontal-tailwind.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import { TngStepperComponent, TngStepperItemComponent } from '@tailng-ui/components';",
        '',
        '@Component({',
        "  selector: 'app-stepper-examples-horizontal-tailwind',",
        '  standalone: true,',
        '  imports: [TngStepperComponent, TngStepperItemComponent],',
        "  templateUrl: './stepper-examples-horizontal-tailwind.component.html',",
        "  styleUrl: './stepper-examples-horizontal-tailwind.component.css',",
        '})',
        'export class StepperExamplesHorizontalTailwindComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'stepper-examples-horizontal-tailwind.component.html',
      code: [
        '<div class="rounded-xl border border-slate-300 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-900/60">',
        '  <tng-stepper orientation="horizontal" defaultValue="plan" ariaLabel="Horizontal onboarding progress">',
        '    <tng-stepper-item value="account" label="Account" completed />',
        '    <tng-stepper-item value="plan" label="Plan" description="Workspace limits" />',
        '    <tng-stepper-item value="invite" label="Invite" description="Optional team setup" optional />',
        '  </tng-stepper>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'stepper-examples-horizontal-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  protected readonly checkoutPlainCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'stepper-examples-checkout-plain-css.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import { TngStepperComponent } from '@tailng-ui/components';",
        "import { TngStepperDescription, TngStepperItem, TngStepperLabel, TngStepperTrigger } from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-stepper-examples-checkout-plain-css',",
        '  standalone: true,',
        '  imports: [TngStepperComponent, TngStepperDescription, TngStepperItem, TngStepperLabel, TngStepperTrigger],',
        "  templateUrl: './stepper-examples-checkout-plain-css.component.html',",
        "  styleUrl: './stepper-examples-checkout-plain-css.component.css',",
        '})',
        'export class StepperExamplesCheckoutPlainCssComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'stepper-examples-checkout-plain-css.component.html',
      code: [
        '<div class="stepper-example-shell stepper-example-shell--plain">',
        '  <tng-stepper ariaLabel="Checkout progress" defaultValue="shipping" linear>',
        '    <ol class="stepper-example-list">',
        '      <li tngStepperItem value="cart" label="Cart" completed class="stepper-example-item">',
        '        <button tngStepperTrigger class="stepper-example-trigger"><span class="dot">1</span><span tngStepperLabel>Cart</span></button>',
        '      </li>',
        '      <li tngStepperItem value="shipping" label="Shipping" class="stepper-example-item">',
        '        <button tngStepperTrigger class="stepper-example-trigger"><span class="dot">2</span><span tngStepperLabel>Shipping</span></button>',
        '      </li>',
        '      <li tngStepperItem value="payment" label="Payment" class="stepper-example-item">',
        '        <button tngStepperTrigger class="stepper-example-trigger"><span class="dot">3</span><span tngStepperLabel>Payment</span></button>',
        '      </li>',
        '    </ol>',
        '  </tng-stepper>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'stepper-examples-checkout-plain-css.component.css',
      code: [
        '.stepper-example-shell--plain {',
        '  border: 1px solid var(--tng-semantic-border-subtle);',
        '  border-radius: 0.8rem;',
        '  padding: 0.9rem 1rem;',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly checkoutTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'stepper-examples-checkout-tailwind.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import { TngStepperComponent } from '@tailng-ui/components';",
        "import { TngStepperDescription, TngStepperItem, TngStepperLabel, TngStepperTrigger } from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-stepper-examples-checkout-tailwind',",
        '  standalone: true,',
        '  imports: [TngStepperComponent, TngStepperDescription, TngStepperItem, TngStepperLabel, TngStepperTrigger],',
        "  templateUrl: './stepper-examples-checkout-tailwind.component.html',",
        "  styleUrl: './stepper-examples-checkout-tailwind.component.css',",
        '})',
        'export class StepperExamplesCheckoutTailwindComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'stepper-examples-checkout-tailwind.component.html',
      code: [
        '<div class="rounded-xl border border-slate-300 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-900/60">',
        '  <tng-stepper ariaLabel="Checkout progress" defaultValue="shipping" linear>',
        '    <ol class="stepper-example-list">',
        '      <li tngStepperItem value="cart" label="Cart" completed class="stepper-example-item">',
        '        <button tngStepperTrigger class="stepper-example-trigger"><span class="dot">1</span><span tngStepperLabel>Cart</span></button>',
        '      </li>',
        '      <li tngStepperItem value="shipping" label="Shipping" class="stepper-example-item">',
        '        <button tngStepperTrigger class="stepper-example-trigger"><span class="dot">2</span><span tngStepperLabel>Shipping</span></button>',
        '      </li>',
        '      <li tngStepperItem value="payment" label="Payment" class="stepper-example-item">',
        '        <button tngStepperTrigger class="stepper-example-trigger"><span class="dot">3</span><span tngStepperLabel>Payment</span></button>',
        '      </li>',
        '    </ol>',
        '  </tng-stepper>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'stepper-examples-checkout-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  protected readonly releasePlainCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'stepper-examples-release-plain-css.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import { TngStepperComponent } from '@tailng-ui/components';",
        "import { TngStepperDescription, TngStepperItem, TngStepperLabel, TngStepperTrigger } from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-stepper-examples-release-plain-css',",
        '  standalone: true,',
        '  imports: [TngStepperComponent, TngStepperDescription, TngStepperItem, TngStepperLabel, TngStepperTrigger],',
        "  templateUrl: './stepper-examples-release-plain-css.component.html',",
        "  styleUrl: './stepper-examples-release-plain-css.component.css',",
        '})',
        'export class StepperExamplesReleasePlainCssComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'stepper-examples-release-plain-css.component.html',
      code: [
        '<div class="stepper-example-shell stepper-example-shell--plain">',
        '  <tng-stepper ariaLabel="Release flow" defaultValue="publish">',
        '    <ol class="stepper-example-list">',
        '      <li tngStepperItem value="draft" label="Draft" completed class="stepper-example-item">',
        '        <button tngStepperTrigger class="stepper-example-trigger"><span class="dot">1</span><span tngStepperLabel>Draft</span></button>',
        '      </li>',
        '      <li tngStepperItem value="review" label="Review" completed class="stepper-example-item">',
        '        <button tngStepperTrigger class="stepper-example-trigger"><span class="dot">2</span><span tngStepperLabel>Review</span></button>',
        '      </li>',
        '      <li tngStepperItem value="publish" label="Publish" class="stepper-example-item">',
        '        <button tngStepperTrigger class="stepper-example-trigger"><span class="dot">3</span><span tngStepperLabel>Publish</span></button>',
        '      </li>',
        '    </ol>',
        '  </tng-stepper>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'stepper-examples-release-plain-css.component.css',
      code: [
        '.stepper-example-item[data-state="completed"] {',
        '  background: color-mix(in srgb, var(--tng-semantic-accent-success) 12%, transparent);',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly releaseTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'stepper-examples-release-tailwind.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import { TngStepperComponent } from '@tailng-ui/components';",
        "import { TngStepperDescription, TngStepperItem, TngStepperLabel, TngStepperTrigger } from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-stepper-examples-release-tailwind',",
        '  standalone: true,',
        '  imports: [TngStepperComponent, TngStepperDescription, TngStepperItem, TngStepperLabel, TngStepperTrigger],',
        "  templateUrl: './stepper-examples-release-tailwind.component.html',",
        "  styleUrl: './stepper-examples-release-tailwind.component.css',",
        '})',
        'export class StepperExamplesReleaseTailwindComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'stepper-examples-release-tailwind.component.html',
      code: [
        '<div class="rounded-xl border border-slate-300 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-900/60">',
        '  <tng-stepper ariaLabel="Release flow" defaultValue="publish">',
        '    <ol class="stepper-example-list">',
        '      <li tngStepperItem value="draft" label="Draft" completed class="stepper-example-item">',
        '        <button tngStepperTrigger class="stepper-example-trigger"><span class="dot">1</span><span tngStepperLabel>Draft</span></button>',
        '      </li>',
        '      <li tngStepperItem value="review" label="Review" completed class="stepper-example-item">',
        '        <button tngStepperTrigger class="stepper-example-trigger"><span class="dot">2</span><span tngStepperLabel>Review</span></button>',
        '      </li>',
        '      <li tngStepperItem value="publish" label="Publish" class="stepper-example-item">',
        '        <button tngStepperTrigger class="stepper-example-trigger"><span class="dot">3</span><span tngStepperLabel>Publish</span></button>',
        '      </li>',
        '    </ol>',
        '  </tng-stepper>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'stepper-examples-release-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  protected readonly errorPlainCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'stepper-examples-error-plain-css.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import { TngStepperComponent } from '@tailng-ui/components';",
        "import { TngStepperDescription, TngStepperItem, TngStepperLabel, TngStepperTrigger } from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-stepper-examples-error-plain-css',",
        '  standalone: true,',
        '  imports: [TngStepperComponent, TngStepperDescription, TngStepperItem, TngStepperLabel, TngStepperTrigger],',
        "  templateUrl: './stepper-examples-error-plain-css.component.html',",
        "  styleUrl: './stepper-examples-error-plain-css.component.css',",
        '})',
        'export class StepperExamplesErrorPlainCssComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'stepper-examples-error-plain-css.component.html',
      code: [
        '<div class="stepper-example-shell stepper-example-shell--plain">',
        '  <tng-stepper ariaLabel="Onboarding" defaultValue="billing">',
        '    <ol class="stepper-example-list">',
        '      <li tngStepperItem value="profile" label="Profile" completed class="stepper-example-item">',
        '        <button tngStepperTrigger class="stepper-example-trigger"><span class="dot">1</span><span tngStepperLabel>Profile</span></button>',
        '      </li>',
        '      <li tngStepperItem value="billing" label="Billing" error class="stepper-example-item">',
        '        <button tngStepperTrigger class="stepper-example-trigger"><span class="dot">2</span><span tngStepperLabel>Billing</span></button>',
        '        <span tngStepperDescription class="stepper-example-description">Card declined</span>',
        '      </li>',
        '      <li tngStepperItem value="invite" label="Team invite" class="stepper-example-item">',
        '        <button tngStepperTrigger class="stepper-example-trigger"><span class="dot">3</span><span tngStepperLabel>Team invite</span></button>',
        '      </li>',
        '    </ol>',
        '  </tng-stepper>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'stepper-examples-error-plain-css.component.css',
      code: [
        '.stepper-example-item[data-state="error"] {',
        '  background: color-mix(in srgb, var(--tng-semantic-accent-danger) 10%, transparent);',
        '}',
      ].join('\n'),
    },
  ]);

  protected readonly errorTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
    {
      value: 'ts',
      label: 'TS',
      language: 'ts',
      title: 'stepper-examples-error-tailwind.component.ts',
      code: [
        "import { Component } from '@angular/core';",
        "import { TngStepperComponent } from '@tailng-ui/components';",
        "import { TngStepperDescription, TngStepperItem, TngStepperLabel, TngStepperTrigger } from '@tailng-ui/primitives';",
        '',
        '@Component({',
        "  selector: 'app-stepper-examples-error-tailwind',",
        '  standalone: true,',
        '  imports: [TngStepperComponent, TngStepperDescription, TngStepperItem, TngStepperLabel, TngStepperTrigger],',
        "  templateUrl: './stepper-examples-error-tailwind.component.html',",
        "  styleUrl: './stepper-examples-error-tailwind.component.css',",
        '})',
        'export class StepperExamplesErrorTailwindComponent {}',
      ].join('\n'),
    },
    {
      value: 'html',
      label: 'HTML',
      language: 'html',
      title: 'stepper-examples-error-tailwind.component.html',
      code: [
        '<div class="rounded-xl border border-slate-300 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-900/60">',
        '  <tng-stepper ariaLabel="Onboarding" defaultValue="billing">',
        '    <ol class="stepper-example-list">',
        '      <li tngStepperItem value="profile" label="Profile" completed class="stepper-example-item">',
        '        <button tngStepperTrigger class="stepper-example-trigger"><span class="dot">1</span><span tngStepperLabel>Profile</span></button>',
        '      </li>',
        '      <li tngStepperItem value="billing" label="Billing" error class="stepper-example-item">',
        '        <button tngStepperTrigger class="stepper-example-trigger"><span class="dot">2</span><span tngStepperLabel>Billing</span></button>',
        '        <span tngStepperDescription class="stepper-example-description">Card declined</span>',
        '      </li>',
        '      <li tngStepperItem value="invite" label="Team invite" class="stepper-example-item">',
        '        <button tngStepperTrigger class="stepper-example-trigger"><span class="dot">3</span><span tngStepperLabel>Team invite</span></button>',
        '      </li>',
        '    </ol>',
        '  </tng-stepper>',
        '</div>',
      ].join('\n'),
    },
    {
      value: 'css',
      label: 'CSS',
      language: 'css',
      title: 'stepper-examples-error-tailwind.component.css',
      code: '/* Tailwind utilities are applied directly in the template. */',
    },
  ]);

  public ngOnDestroy(): void {
    this.colorSchemeObserver?.disconnect();
  }
}
