import type { DocsExampleCodeTab } from '../../../../../../shared/example-panel/docs-example-panel.component';

const customNodeComponentCode = [
  "import { Component, signal } from '@angular/core';",
  'import {',
  '  TngCardComponent,',
  '  TngCardContentComponent,',
  '  TngCardDescriptionComponent,',
  '  TngCardHeaderComponent,',
  '  TngCardTitleComponent,',
  "} from '@tailng-ui/components';",
  'import {',
  '  TngFlowEditorComponent,',
  '  TngFlowNodeTemplateDirective,',
  "} from '@tailng-ui/flow';",
  "import { agentConnections, agentNodes, agentViews } from './agent-flow.data';",
  '',
  '@Component({',
  "  selector: 'app-custom-agent-flow',",
  '  standalone: true,',
  '  imports: [',
  '    TngCardComponent,',
  '    TngCardContentComponent,',
  '    TngCardDescriptionComponent,',
  '    TngCardHeaderComponent,',
  '    TngCardTitleComponent,',
  '    TngFlowEditorComponent,',
  '    TngFlowNodeTemplateDirective,',
  '  ],',
  "  templateUrl: './custom-agent-flow.component.html',",
  '})',
  'export class CustomAgentFlowComponent {',
  '  protected readonly nodes = signal(agentNodes);',
  '  protected readonly connections = agentConnections;',
  '  protected readonly nodeViews = agentViews;',
  '}',
].join('\n');

const customNodePlainMarkup = [
  '<tng-flow-editor',
  '  flowId="custom-agent-flow"',
  '  class="agent-flow"',
  '  [nodes]="nodes()"',
  '  [connections]="connections"',
  '  [nodeViews]="nodeViews"',
  '>',
  '  <ng-template tngFlowNode="model" let-node let-view="view" let-selected="selected">',
  '    <tng-card class="model-node" tone="primary" [elevated]="selected">',
  '      <tng-card-header>',
  '        <span class="model-node__eyebrow">Reasoning step</span>',
  '        <tng-card-title>{{ node.name }}</tng-card-title>',
  '        <tng-card-description>{{ node.description }}</tng-card-description>',
  '      </tng-card-header>',
  '      <tng-card-content>',
  '        <p>{{ node.data.detail }}</p>',
  '        <span class="model-node__status">',
  "          {{ view.status ?? 'idle' }} · {{ view.progress ?? 0 }}%",
  '        </span>',
  '      </tng-card-content>',
  '    </tng-card>',
  '  </ng-template>',
  '</tng-flow-editor>',
].join('\n');

const customNodeTailwindMarkup = [
  '<tng-flow-editor',
  '  flowId="custom-agent-flow"',
  '  class="block h-[29rem] min-h-[24rem]"',
  '  [nodes]="nodes()"',
  '  [connections]="connections"',
  '  [nodeViews]="nodeViews"',
  '>',
  '  <ng-template tngFlowNode="model" let-node let-view="view" let-selected="selected">',
  '    <tng-card class="block w-[17.5rem]" tone="primary" [elevated]="selected">',
  '      <tng-card-header>',
  '        <span class="text-[0.675rem] font-bold uppercase tracking-[0.1em] text-blue-500">',
  '          Reasoning step',
  '        </span>',
  '        <tng-card-title>{{ node.name }}</tng-card-title>',
  '        <tng-card-description>{{ node.description }}</tng-card-description>',
  '      </tng-card-header>',
  '      <tng-card-content>',
  '        <p class="m-0 text-sm text-slate-600 dark:text-slate-300">{{ node.data.detail }}</p>',
  '        <span',
  '          class="mt-3 inline-flex rounded-full bg-blue-500/10 px-2 py-1 text-xs font-semibold capitalize text-blue-500"',
  '        >',
  "          {{ view.status ?? 'idle' }} · {{ view.progress ?? 0 }}%",
  '        </span>',
  '      </tng-card-content>',
  '    </tng-card>',
  '  </ng-template>',
  '</tng-flow-editor>',
].join('\n');

const customNodePlainCss = [
  '.agent-flow {',
  '  display: block;',
  '  height: 29rem;',
  '  min-height: 24rem;',
  '}',
  '',
  '.model-node {',
  '  display: block;',
  '  width: 17.5rem;',
  '}',
  '',
  '.model-node__eyebrow {',
  '  color: var(--tng-semantic-accent-brand);',
  '  font-size: 0.675rem;',
  '  font-weight: 700;',
  '  letter-spacing: 0.1em;',
  '  text-transform: uppercase;',
  '}',
  '',
  '.model-node__status {',
  '  background: color-mix(in srgb, var(--tng-semantic-accent-brand) 12%, transparent);',
  '  border-radius: 999px;',
  '  color: var(--tng-semantic-accent-brand);',
  '  display: inline-flex;',
  '  margin-top: 0.75rem;',
  '  padding: 0.2rem 0.55rem;',
  '  text-transform: capitalize;',
  '}',
].join('\n');

const monitorComponentCode = [
  "import { Component } from '@angular/core';",
  "import { TngFlowEditorComponent } from '@tailng-ui/flow';",
  "import { executionConnections, executionNodes, executionViews } from './execution.data';",
  '',
  '@Component({',
  "  selector: 'app-execution-monitor',",
  '  standalone: true,',
  '  imports: [TngFlowEditorComponent],',
  "  templateUrl: './execution-monitor.component.html',",
  '})',
  'export class ExecutionMonitorComponent {',
  '  protected readonly nodes = executionNodes;',
  '  protected readonly connections = executionConnections;',
  '  protected readonly views = executionViews;',
  '}',
].join('\n');

const monitorMarkup = [
  '<tng-flow-editor',
  '  flowId="execution-monitor"',
  '  [nodes]="nodes"',
  '  [connections]="connections"',
  '  [nodeViews]="views"',
  '  [readonly]="true"',
  '  [showSelectionArea]="false"',
  '/>',
].join('\n');

export const customNodePlainCssCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
  {
    value: 'ts',
    label: 'TS',
    language: 'ts',
    title: 'custom-agent-flow.component.ts',
    code: customNodeComponentCode,
  },
  {
    value: 'html',
    label: 'HTML',
    language: 'html',
    title: 'custom-agent-flow.component.html',
    code: customNodePlainMarkup,
  },
  {
    value: 'css',
    label: 'CSS',
    language: 'css',
    title: 'custom-agent-flow.component.css',
    code: customNodePlainCss,
  },
]);

export const customNodeTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
  {
    value: 'ts',
    label: 'TS',
    language: 'ts',
    title: 'custom-agent-flow.component.ts',
    code: customNodeComponentCode,
  },
  {
    value: 'html',
    label: 'HTML',
    language: 'html',
    title: 'custom-agent-flow.component.html',
    code: customNodeTailwindMarkup,
  },
  {
    value: 'css',
    label: 'CSS',
    language: 'css',
    title: 'custom-agent-flow.component.css',
    code: '/* Tailwind utilities are applied directly in the template. */',
  },
]);

export const monitorPlainCssCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
  {
    value: 'ts',
    label: 'TS',
    language: 'ts',
    title: 'execution-monitor.component.ts',
    code: monitorComponentCode,
  },
  {
    value: 'html',
    label: 'HTML',
    language: 'html',
    title: 'execution-monitor.component.html',
    code: monitorMarkup.replace('flowId=', 'class="execution-monitor"\n  flowId='),
  },
  {
    value: 'css',
    label: 'CSS',
    language: 'css',
    title: 'execution-monitor.component.css',
    code: [
      '.execution-monitor {',
      '  display: block;',
      '  height: 29rem;',
      '  min-height: 24rem;',
      '}',
    ].join('\n'),
  },
]);

export const monitorTailwindCodeTabs: readonly DocsExampleCodeTab[] = Object.freeze([
  {
    value: 'ts',
    label: 'TS',
    language: 'ts',
    title: 'execution-monitor.component.ts',
    code: monitorComponentCode,
  },
  {
    value: 'html',
    label: 'HTML',
    language: 'html',
    title: 'execution-monitor.component.html',
    code: monitorMarkup.replace('flowId=', 'class="block h-[29rem] min-h-[24rem]"\n  flowId='),
  },
  {
    value: 'css',
    label: 'CSS',
    language: 'css',
    title: 'execution-monitor.component.css',
    code: '/* Tailwind utilities are applied directly in the template. */',
  },
]);
